S1 us5/feature card
WildCodeSchool/2023-09-js-tlse-p2-el-jefe pull request #2
Opened 2023-11-07 15:48 UTC by marcDjango

2023-11-07 16:08 UTC, Adri-bis requested changes

2023-11-07 16:08 UTC, Adri-bis commented on frontend/src/App.css
> +h2 {
A enlever et mettre dans une fiche css plus appropriate

2023-11-07 16:08 UTC, Adri-bis commented on frontend/src/App.jsx
> +    // ************** Component Card*************************
Mets ça dans un autre composant s'il te plais cordialement

2023-11-07 16:08 UTC, Adri-bis commented on frontend/src/components/card/card.jsx
> +// import style card
Code mort .

2023-11-07 16:08 UTC, Adri-bis commented on frontend/src/services/api/config.json
> +{
A mettre dans un .env, donnée sensible

2023-11-08 08:28 UTC, Adri-bis approved these changes
C'est ok

2023-11-08 08:54 UTC, ArthurHtbk requested changes
On y est presque !

2023-11-08 08:54 UTC, ArthurHtbk commented on frontend/src/components/AllCards/AllCards.jsx
> +  return (
Le code est répétitif ici. Il y aurait peut-être moyen de faire un composant que tu appelles 4 fois non ? 🙂

2023-11-08 14:13 UTC, ArthurHtbk approved these changes

2023-11-08 14:13 UTC, merged