S2 us01/navbar
WildCodeSchool/2023-09-js-tlse-p2-el-jefe pull request #3
Opened 2023-11-08 16:02 UTC by Adri-bis

2023-11-08 16:07 UTC, marcDjango approved these changes

2023-11-08 16:21 UTC, ArthurHtbk requested changes
J'ai laissé les commentaires là où il faut, et de manière générale fais attention à l'organisation de ton code : les states avec les states, les useEffect avec les useEffect, etc.

2023-11-08 16:21 UTC, ArthurHtbk commented on frontend/src/App.jsx
> +      <img src={planche} className="planche" alt="planche à decoupé" />
Attention à l'orthographe/syntaxe dans l'attribut alt => Planche à découper

2023-11-08 16:21 UTC, ArthurHtbk commented on frontend/src/components/Navbar/Navbar.jsx
> +  const [hamburOpen, setHamberOpen] = useState(false);
Attention aux noms de state => `[isHamburgerOpen, setIsHamburgerOpen]`

2023-11-08 16:21 UTC, ArthurHtbk commented on frontend/src/components/Navbar/Navbar.jsx
> +  const [isCategoriOpen, setIsCategoriOpen] = useState(true);
Attention aux noms de state => `[isCategoryOpen, setIsCategoryOpen]`

2023-11-08 16:21 UTC, ArthurHtbk commented on frontend/src/components/Navbar/Navbar.jsx
> +  const toggleCatégori = () => {
Attention aux noms de fonctions => `toggleCategory`

2023-11-08 16:21 UTC, ArthurHtbk commented on frontend/src/components/Navbar/Navbar.jsx
> +                      <Link to="/categorie">Breackfast</Link>
Attention à l'orthographe => Breakfast

2023-11-08 16:21 UTC, ArthurHtbk commented on frontend/src/components/Navbar/Navbar.jsx
> +                    <Link to="/categorie">Breackfast</Link>
Attention à l'orthographe => Breakfast

2023-11-08 16:21 UTC, ArthurHtbk commented on frontend/src/main.jsx
> +import Aboutus from "./pages/Aboutus";
Attention à la casse, les composants sont typiquement écrits en pascal case => `AboutUs`

2023-11-08 16:21 UTC, ArthurHtbk commented on frontend/src/main.jsx
> +import Thinkabout from "./pages/Thinkabout";
Attention à la casse, les composants sont typiquement écrits en pascal case => `ThinkAbout`

2023-11-08 16:21 UTC, ArthurHtbk commented on frontend/src/main.jsx
> +import Categorie from "./pages/Categorie";
Attention aux noms de fichier, en anglais plutôt qu'en français => `Category`

2023-11-08 16:21 UTC, ArthurHtbk commented on frontend/src/pages/Aboutus.jsx
> +  return <div>Comming soon</div>;
`Comming soon` => `Coming soon`

2023-11-08 16:21 UTC, ArthurHtbk commented on frontend/src/pages/Categorie.jsx
> +  return <div>Comming soon</div>;
`Comming soon` => `Coming soon`

2023-11-08 16:21 UTC, ArthurHtbk commented on frontend/src/pages/Nutriscore.jsx
> +  return <div>Comming soon</div>;
`Comming soon` => `Coming soon`

2023-11-08 16:21 UTC, ArthurHtbk commented on frontend/src/pages/Thinkabout.jsx
> +  return <div>Comming soon</div>;
`Comming soon` => `Coming soon`

2023-11-09 08:33 UTC, ArthurHtbk requested changes

2023-11-09 08:33 UTC, ArthurHtbk commented on frontend/src/components/Navbar/Navbar.jsx
> +  const toglleBurger = () => {
Attention => `toggleBurger`

2023-11-09 08:33 UTC, ArthurHtbk commented on frontend/src/components/Navbar/Navbar.jsx
> +  const toglleCategory = () => {
Attention => `toggleCategory`

2023-11-09 08:33 UTC, ArthurHtbk commented on frontend/src/components/Navbar/Navbar.jsx
Il faudrait réorganiser ce fichier en composants pour éviter les répétitions ! 🙂

2023-11-09 10:02 UTC, 6sous approved these changes
Ok, à voir pour le "ListCat a" en display flex

2023-11-09 10:04 UTC, 6sous approved these changes

2023-11-09 11:19 UTC, ArthurHtbk approved these changes

2023-11-09 11:19 UTC, merged